// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyShop.Server.Data;

#nullable disable

namespace PharmacyShop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220506104746_Categories")]
    partial class Categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PharmacyShop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vitamins",
                            Url = "vitamins"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antipyretics",
                            Url = "antipyretics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Digestion",
                            Url = "digestion"
                        });
                });

            modelBuilder.Entity("PharmacyShop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Vitamin C nutritional supplement with gradual release for the proper functioning of the immune system.",
                            ImageUrl = "https://www.drmax.sk/_i/288425126.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2F6%2Fz%2F6zdiiq0_400x400_1.jpg&fit=contain&w=350&h=350&format=webp",
                            Price = 4.99m,
                            Title = "Vitamin C Long Effect 500 mg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Advantageous package with gelatin capsules with vitamin D3.",
                            ImageUrl = "https://www.drmax.sk/_i/1851874929.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fd%2Fe%2Fdevit_2000_120_l.png&fit=contain&w=350&h=350&format=webp",
                            Price = 11.49m,
                            Title = "Vitamin D DeVit 2000 IU"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "It contains a combination of magnesium and vitamin B6, thanks to which magnesium is replenished in the body faster. Magne B6® improves in case of magnesium deficiency e.g. nervousness, fatigue, irritability, muscle cramps and numbness.",
                            ImageUrl = "https://www.drmax.sk/_i/1922185717.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fz%2Fp%2Fzpv4rz0_400x400_1.jpg&fit=contain&w=350&h=350&format=webp",
                            Price = 14.39m,
                            Title = "Magne B6"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Probiotic complex suitable for adults and children from 3 years.",
                            ImageUrl = "https://www.drmax.sk/_i/1944578361.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fo%2Fz%2Fozz0lb0_400x400_1.jpg&fit=contain&w=350&h=350&format=webp",
                            Price = 13.39m,
                            Title = "Biopron 9"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Nutritional supplement that contains lyophilized collagen. Suitable as nutrition for cartilage, ligaments, joint capsule, tooth nails, skin.",
                            ImageUrl = "https://www.drmax.sk/_i/-145592899.jpg?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fj%2Fz%2Fjzn3he0_400x400_1.jpg&fit=contain&w=350&h=350&format=jpg",
                            Price = 9.39m,
                            Title = "Colafit"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Drug with analgesic and antipyretic effect. Helps relieve pain and lower temperature. Suitable for flu conditions. It does not irritate the stomach.",
                            ImageUrl = "https://www.drmax.sk/_i/-1194474228.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fp%2Fa%2Fparalen_500_24tab.png&fit=contain&w=350&h=350&format=webp",
                            Price = 2.09m,
                            Title = "Paralen 500"
                        });
                });

            modelBuilder.Entity("PharmacyShop.Shared.Product", b =>
                {
                    b.HasOne("PharmacyShop.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
